---
- name: change the OU of Newly create Server
  hosts: ad_host_name
  tasks:
    - name: wait for server to get DNS resolution
      shell: nslookup -vc {{item.vm_name}}.domain.com.bh {{DNS_Server_IP}}
      register: name_resolve
      until: name_resolve.stdout.find("{{item.vm_ip}}") != -1
      retries: 5
      delay: 300
      delegate_to: 127.0.0.1
      with_items:
        - "{{vmdetails}}"
    - name: Ensure The server is in right OU
      win_shell: Move-ADObject –Identity "CN={{item.vm_name}},CN=Computers,DC=domain,DC=com,DC=bh" -TargetPath "OU=Domain Servers,DC=domain,DC=com,DC=bh"
      with_items:
        - "{{ vmdetails }}"
        
